// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jobs": {
    params: {};
  };
  "/jobs/:jobId": {
    params: {
      "jobId": string;
    };
  };
  "/jobs/:jobId/job-materials/:jobMaterialId": {
    params: {
      "jobId": string;
      "jobMaterialId": string;
    };
  };
  "/jobs/:jobId/new-job-material": {
    params: {
      "jobId": string;
    };
  };
  "/learn": {
    params: {};
  };
  "/learn/:section/:page": {
    params: {
      "section": string;
      "page": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/activate": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/refresh": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jobs" | "/jobs/:jobId" | "/jobs/:jobId/job-materials/:jobMaterialId" | "/jobs/:jobId/new-job-material" | "/learn" | "/learn/:section/:page" | "/login" | "/register" | "/activate" | "/forgot-password" | "/logout" | "/refresh";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/jobs/jobs-home.tsx": {
    id: "routes/jobs/jobs-home";
    page: "/jobs";
  };
  "routes/jobs/job-layout.tsx": {
    id: "routes/jobs/job-layout";
    page: "/jobs/:jobId" | "/jobs/:jobId/job-materials/:jobMaterialId" | "/jobs/:jobId/new-job-material";
  };
  "routes/jobs/job-upload.tsx": {
    id: "routes/jobs/job-upload";
    page: "/jobs/:jobId";
  };
  "routes/jobs/job-material-detail.tsx": {
    id: "routes/jobs/job-material-detail";
    page: "/jobs/:jobId/job-materials/:jobMaterialId";
  };
  "routes/jobs/new-job-material.tsx": {
    id: "routes/jobs/new-job-material";
    page: "/jobs/:jobId/new-job-material";
  };
  "routes/learn.tsx": {
    id: "routes/learn";
    page: "/learn";
  };
  "routes/learn/learn-layout.tsx": {
    id: "routes/learn/learn-layout";
    page: "/learn/:section/:page";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/auth/activate.tsx": {
    id: "routes/auth/activate";
    page: "/activate";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/logout";
  };
  "routes/auth/refresh.tsx": {
    id: "routes/auth/refresh";
    page: "/refresh";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/jobs/jobs-home": typeof import("./app/routes/jobs/jobs-home.tsx");
  "routes/jobs/job-layout": typeof import("./app/routes/jobs/job-layout.tsx");
  "routes/jobs/job-upload": typeof import("./app/routes/jobs/job-upload.tsx");
  "routes/jobs/job-material-detail": typeof import("./app/routes/jobs/job-material-detail.tsx");
  "routes/jobs/new-job-material": typeof import("./app/routes/jobs/new-job-material.tsx");
  "routes/learn": typeof import("./app/routes/learn.tsx");
  "routes/learn/learn-layout": typeof import("./app/routes/learn/learn-layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/auth/activate": typeof import("./app/routes/auth/activate.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.tsx");
  "routes/auth/refresh": typeof import("./app/routes/auth/refresh.tsx");
};